# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ea6cc807449712d4a07932a29e62dde55d8f39d264c8adbba6d26caac7281afa786839f6949cb8b5b13f28d495e5fcdccaa675d6de76442257388980a8b61c0

test:
  secret_key_base: e06f4c670ee2c6ca9d1faec400a7f44cf06427baf334306ccaf1996c0a57f2689a24ccbbf97990c700e692f19c864cdf55ceeaf9f980296c5be4d38581ceb327

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
